##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

## Note: Any command which fails in any stage below result in the command stopping, and endStage being run.
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.

globalVariables:
  DRY_RUN: ${DRY_RUN:-false}

stages:
  Validation:
    actions: 
      - type: liquibase
        command: validate

  Checks-Changelog:
    actions:
      - type: liquibase
        command: checks run
        cmdArgs: {checks-scope: changelog, context-filter: DEV}
        globalArgs: { reports-name: "checks-report-build-changelog.html" }
         
  Status:
    actions:
      - type: liquibase
        command: status
        cmdArgs: {verbose: true, context-filter: DEV}

  Update-SQL:
    actions:
      - type: liquibase
        command: update-sql
        cmdArgs: {context-filter: DEV, reports-name: "dryrun-report.html"}

  Echo:
    actions:
      - type: shell
        command: echo 'Value of DRY_RUN variable ${DRY_RUN}'
        
  Update:  
    actions:
      - type: liquibase
        if: "${DRY_RUN} == false"
        command: update
        cmdArgs: {context-filter: DEV}
        globalArgs: { reports-name: "build-report.html" }

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: history